### ISSUE TITLE
Reading pcap files

### ISSUE THREAD

**Issue by jcgomes90** [DevQps/bgp-rs#22]
Does this library support reading in pcap files?

**Comment by thepacketgeek** [comment]
@jcgomes90 this is delayed but hopefull this info is still useful to you:

This crate doesn't support reading pcap files directly, but using the [pcap_file crate](https://crates.io/crates/pcap-file), you can see how to parse BGP messages from pcaps by looking at the [test utils module](https://github.com/DevQps/bgp-rs/blob/master/tests/common/mod.rs)

**Comment by DevQps** [comment]
I can also write an example for this in the README or main crate maybe!
