### ISSUE TITLE
crates.io release

### ISSUE THREAD

**Issue by ccakes** [DevQps/bgp-rs#32]
Hi! 👋 

Thanks for pulling all the work on this crate into one place - awesome stuff. Do you have any plans for a crate.io release at all? I have some BMP work that I'd like to tidy up and publish but can't with a git-based dependency

Happy to help with anything if needed

**Comment by DevQps** [comment]
We have plans to do a new release soon! @thepacketgeek is currently working to put the flowspec encoding behind a separate feature flag. And I hope to crrate a PR to migrate to GitHub Actions today. We were also thinking about changing `dyn Read` to `impl Read` were possible to potentially speedup performance since only one or just a few type of Read instances are usually used.

Do you have any suggestions yourself before we release a new version?

**Comment by ccakes** [comment]
🥳 

Nothing from me at the moment - I've just today started testing `master` and all seems good 👍 I've got some flowspec plans as well but that's waiting on me to have some time to spend on a new project..

**Comment by DevQps** [comment]
In the end, yesterday was a busy day... I hope to have more time on Saturday to create the initial PR!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ccakes** [comment]
Actually one change - `Notification::parse()` is still private. Would be good to make that public inline with Open and Update messages

https://github.com/DevQps/bgp-rs/blob/95d2b250d90b03c021d2a0298a97eefef366a7af/src/notification.rs#L20

**Comment by DevQps** [comment]
Thanks for the mentioning this! I will take this with me when I start working on this!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by DevQps** [comment]
> 
> 
> Actually one change - `Notification::parse()` is still private. Would be good to make that public inline with Open and Update messages
> 
> https://github.com/DevQps/bgp-rs/blob/95d2b250d90b03c021d2a0298a97eefef366a7af/src/notification.rs#L20

@thepacketgeek Maybe you could include this in your PR as well? Only if it's not too much trouble!

@ccakes I just created the Actions Pipeline today and I saw that Mat created his PR as well. So I hope we can release a new version soon.

**Comment by thepacketgeek** [comment]
Yes, I will change `Notification::parse()` to pub in #33 and rebase over #34 when it is merged

**Comment by ccakes** [comment]
@thepacketgeek thanks for that! 🙏

**Comment by thepacketgeek** [comment]
I don't think this is release blocking, but I just added #35 to add a minimum support rust version (1.34.2)

**Comment by DevQps** [comment]
I think we're very close to a new release!

@ccakes @thepacketgeek @TheBlueMatt Do you still see room for improvement before we do a new release? I think we can release a 1.0.0 now? Or do you think a 0.6.0 would be more appropriate?

I will write some last documentation on Saterday and if you all agree with that PR and think we're ready for a new release, we can bump the version and publish it.

**Comment by thepacketgeek** [comment]
I think 0.6.0 is good for now :) I'm also working on adding unittests to bump up the coverage a bit.

**Comment by ccakes** [comment]
Apologies for the delay - I have nothing extra to add for a release.

**Comment by DevQps** [comment]
Since 0.6.0 has been released for a while I will close this now!
